["choked like a dog",
"a mixed up man who doesn't have a clue. No wonder he lost!",
"Failed",
"the man who ‘choked' and let us all down",
"Failed presidential candidate",
"let us all down in the last presidential race",
"a total joke, and everyone knows it!",
"a disaster candidate who had no guts and choked",
"Why did Mitt Romney BEG me for my endorsement four years ago?",
"doesn't know how to win",
"desperate move by the man who should have easily beaten Barrack Obama",
"Failed Presidential Candidate",
"didn't show his tax return until SEPTEMBER 21, 2012, and then only after being humiliated by Harry R",
"bad messenger for estab!",
"failed",
"one of the dumbest and worst candidates in the history of Republican politics",
"so awkward and goofy",
"I don't need his angry advice",
"blew an election that should have never been lost",
"terrible 'choke' loss to Obama",
"he choked!",
"lost an election that should have easily been won",
"why would anybody listen to @MittRomney?"]
